name: FirstGitHubActions Build and Test

#Triggers (uncomment line below to use it)
on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"
          dotnet-quality: "preview"

      - name: Build with dotnet
        run: dotnet build ./FirstGitHubActions/FirstGitHubActions.slnx --configuration Release

      - name: Test with dotnet
        #run: dotnet test ./FirstGitHubActions/FirstGitHubActions.slnx --configuration Release
        run: dotnet test --solution ./FirstGitHubActions/FirstGitHubActions.slnx
