name: CI Pipeline develop

on:
  push: # Отправка
    branches: [develop] #ветви отправки
  #pull_request: #Наверное публикация
  # branches: [main] #ветвь из которой публикуется проект

env: #среда
  DOTNET_VERSION: "10.0.x" #версия dotnet
  NODE_VERSION: "24" #версия node.js

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for better analysis

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          #key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/FirstGitHubActions.Tests.csproj') }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          fail_ci_if_error: true

  security-scan: #проверка безопасности
    name: Security Analysis #анализ безопасности
    runs-on: ubuntu-latest #последняя версия ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run security scan
        uses: github/codeql-action/init@v3
        with:
          languages: csharp

      - name: Build for analysis
        run: dotnet build --configuration Release

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3
        
  build-artifacts:
    name: Build Release Artifacts #созд. артефактов с конф. сборки Release, только из основной ветви   
    needs: [test, security-scan] #условия: Должны быть пройдены тесты и проверка безопасности 
    runs-on: ubuntu-latest #создание артефактов на последней версии ubuntu 
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build release package
        run: dotnet publish --configuration Release --output ./release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-package
          path: ./release
          retention-days: 10
